name: Translate Plugin
Description: 'Action to translate a Jeedom Plugin'

inputs:
  deepl_api_key:  # id of input
    description: 'deepl API KEY for automatic translation'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # Checks-out plugin repository under $GITHUB_WORKSPACE
    - name: "Checkout plugin files"
      uses: actions/checkout@v4
      with:
        path: 'plugin'

    - name: "Checkout jeedomThirdPartyDevs/plugins-translations sources"
      uses: actions/checkout@v4
      with:
        repository: 'jeedomThirdPartyDevs/plugins-translations'
        path: 'plugins_translations'

    - name: "Checkout jeedomThirdPartyDevs/plugins-translations-memory for memory translations"
      uses: actions/checkout@v4
      with:
        repository: 'jeedomThirdPartyDevs/plugins-translations-memory'
        path: 'plugins_translations_memory'

    - name: "Checkout jeedom/core for default translations"
      uses: actions/checkout@v4
      with:
        repository: 'jeedom/core'
        ref: 'alpha'
        path: 'jeedom_core'

    - name: "Setup python 3.12"
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r plugins_translations/requirements.txt
      shell: bash

    - name: "Generate translations..."
      shell: bash
      run: |
        ls -la
        python --version
        python plugins_translations/src/translate_plugin.py ${{ inputs.deepl_api_key != '' && format('--deepl_api_key {0}', inputs.deepl_api_key) || ''}}

    - name: "Create Pull Request to plugin..."
      uses: peter-evans/create-pull-request@v6
      with:
        path: 'plugin'
        branch: translations
        delete-branch: true
        add-paths: |
          core/i18n/*.json
          plugin_info/info.json
        title: "Update translations"
        body: "Automated translations done by [jeedomThirdPartyDevs/plugins-translations workflow](https://github.com/jeedomThirdPartyDevs/plugins-translations)"
        commit-message: "Auto update translation done by jeedomThirdPartyDevs/plugins-translations workflow"