name: get core translations

on:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest

    steps:
      - name: Clone jeedom/core alpha
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'jeedom'
          repository: 'core'
          branch: 'alpha'
          depth: 1
      - name: Access cloned repository content
        run: |
          pwd
          cd core/core/i18n
          ls -la
      - uses: actions/checkout@v4
        with:
          path: 'translations'

      - name: Compile all translations prompts
        run: |
          pwd
          ls -la /home
          # python .github/workflows/compile_translations.py --source /home/core/core/i18n --destination $GITHUB_WORKSPACE

      - name: "commit change"
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || (git add *.json && git commit -m 'update translation')
          git push