name: translate

# Controls when the workflow will run
on:
  workflow_call:

env:
  mips2648-translations: "mips2648-translations"

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'Mips2648/jeedom-translations'
          path: ${{ env.mips2648-translations }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run script
        run: |
          python --version
          python ${{ env.mips2648-translations }}/src/translate_plugin.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "update-translations"
          delete-branch: true
          add-paths: core/i18n/*.json
